version: '3'

services:
  database:
    image: docker.io/mysql:8
    environment:
      - "MYSQL_DATABASE=backend"
      - "MYSQL_USER=backend"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"
  redis:
    image: docker.io/redis:6.2-alpine
    environment:
      - "MASTER=true"
    ports:
      - "6379:6379"
    command:
      - "redis-server"
