[advisories]
version = 2
ignore = [
    "RUSTSEC-2023-0071", # Marvin attack
]

[licenses]
version = 2
confidence-threshold = 1.0
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "MPL-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
]
exceptions = [
    { allow = ["OpenSSL"], crate = "ring" },
    { allow = ["Unicode-DFS-2016"], crate = "unicode-ident" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[bans]
multiple-versions = "allow"
deny = [
    { crate = "openssl", use-instead = "rustls" },
    { crate = "openssl-sys", use-instead = "rustls" },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]
