[advisories]
version = 2
ignore = [
    "RUSTSEC-2023-0071", # Marvin attack
]

[licenses]
version = 2
confidence-threshold = 1.0
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "MPL-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Zlib",
    "Unicode-3.0",
]
exceptions = [
    { allow = ["CDLA-Permissive-2.0"], crate = "webpki-roots" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[bans]
multiple-versions = "allow"
deny = [
    { crate = "openssl", use-instead = "rustls" },
    { crate = "openssl-sys", use-instead = "rustls" },
]
