//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "canteen_pivot_menus_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub data_id: u32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub menu_id: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::canteen_menus::Entity",
        from = "Column::MenuId",
        to = "super::canteen_menus::Column::Id"
    )]
    Menu,
    #[sea_orm(
        belongs_to = "super::canteen_data::Entity",
        from = "Column::DataId",
        to = "super::canteen_data::Column::Id"
    )]
    Data,
}

impl ActiveModelBehavior for ActiveModel {}
