//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, Eq, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "events_data")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub date_from: DateTime,
    pub date_to: DateTime,
    #[sea_orm(column_type = "String(StringLen::N(191))")]
    pub title: String,
    #[sea_orm(column_type = "String(StringLen::N(191))")]
    pub description: Option<String>,
    #[sea_orm(column_type = "String(StringLen::N(7))")]
    pub color: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
