//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

pub mod prelude;

pub mod canteen_data;
pub mod canteen_menus;
pub mod canteen_pivot_menus_data;
pub mod colleagues_data;
pub mod events_data;
pub mod menu_items;
pub mod migrations;
pub mod model_has_permissions;
pub mod model_has_roles;
pub mod newsletter;
pub mod pages;
pub mod password_resets;
pub mod permissions;
pub mod posts_authors;
pub mod posts_data;
pub mod posts_labels;
pub mod posts_pivot_labels_data;
pub mod role_has_permissions;
pub mod roles;
pub mod users;
