//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

pub mod prelude;

pub mod canteen_data;
pub mod canteen_menus;
pub mod canteen_pivot_menus_data;
pub mod colleagues_data;
pub mod events_data;
pub mod menu_items;
pub mod pages;
pub mod posts_authors;
pub mod posts_data;
pub mod posts_labels;
pub mod posts_pivot_labels_data;
