//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "model_has_permissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub permission_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub model_type: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub model_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
