//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, Eq, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "posts_data")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub color: String,
    pub description: Option<String>,
    pub content: Option<String>,
    pub index_image: Option<String>,
    pub author_id: Option<i32>,
    pub images: Json,
    pub date: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub featured: i8,
    pub published: i8,
    #[sea_orm(column_name = "previewToken")]
    pub preview_token: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
