//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, Eq, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "posts_data")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(column_type = "String(StringLen::N(191))")]
    pub title: String,
    #[sea_orm(column_type = "String(StringLen::N(7))")]
    pub color: String,
    #[sea_orm(column_type = "Text")]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub content: Option<String>,
    #[sea_orm(column_type = "String(StringLen::N(191))")]
    pub index_image: Option<String>,
    pub author_id: Option<u32>,
    pub images: Json,
    pub date: Option<Date>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub featured: i8,
    pub published: i8,
    #[sea_orm(
        column_name = "previewToken",
        column_type = "String(StringLen::N(191))"
    )]
    pub preview_token: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
