//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, Eq, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "posts_pivot_labels_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub labels_id: u32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub posts_id: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::posts_data::Entity",
        from = "Column::PostsId",
        to = "super::posts_data::Column::Id"
    )]
    Posts,
    #[sea_orm(
        belongs_to = "super::posts_labels::Entity",
        from = "Column::LabelsId",
        to = "super::posts_labels::Column::Id"
    )]
    Labels,
}

impl ActiveModelBehavior for ActiveModel {}
