//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

#![allow(unused_imports)]

pub use super::canteen_data::Entity as CanteenData;
pub use super::canteen_menus::Entity as CanteenMenus;
pub use super::canteen_pivot_menus_data::Entity as CanteenPivotMenusData;
pub use super::colleagues_data::Entity as ColleaguesData;
pub use super::events_data::Entity as EventsData;
pub use super::menu_items::Entity as MenuItems;
pub use super::pages::Entity as Pages;
pub use super::posts_authors::Entity as PostsAuthors;
pub use super::posts_data::Entity as PostsData;
pub use super::posts_labels::Entity as PostsLabels;
pub use super::posts_pivot_labels_data::Entity as PostsPivotLabelsData;
