//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

pub use super::canteen_data::Entity as CanteenData;
pub use super::canteen_menus::Entity as CanteenMenus;
pub use super::canteen_pivot_menus_data::Entity as CanteenPivotMenusData;
pub use super::colleagues_data::Entity as ColleaguesData;
pub use super::events_data::Entity as EventsData;
pub use super::menu_items::Entity as MenuItems;
pub use super::migrations::Entity as Migrations;
pub use super::model_has_permissions::Entity as ModelHasPermissions;
pub use super::model_has_roles::Entity as ModelHasRoles;
pub use super::newsletter::Entity as Newsletter;
pub use super::pages::Entity as Pages;
pub use super::password_resets::Entity as PasswordResets;
pub use super::permissions::Entity as Permissions;
pub use super::posts_authors::Entity as PostsAuthors;
pub use super::posts_data::Entity as PostsData;
pub use super::posts_labels::Entity as PostsLabels;
pub use super::posts_pivot_labels_data::Entity as PostsPivotLabelsData;
pub use super::role_has_permissions::Entity as RoleHasPermissions;
pub use super::roles::Entity as Roles;
pub use super::users::Entity as Users;
