ALTER TABLE `pages`
	MODIFY COLUMN `content`    TEXT     NOT NULL,
	MODIFY COLUMN `extras`     JSON     NOT NULL,
	MODIFY COLUMN `created_at` DATETIME NOT NULL,
	MODIFY COLUMN `updated_at` DATETIME NOT NULL,
	MODIFY COLUMN `deleted_at` DATETIME NULL;
