ALTER TABLE `posts_data`
	MODIFY COLUMN `images`     JSON     NOT NULL,
	MODIFY COLUMN `date`       DATETIME     NULL,
	MODIFY COLUMN `created_at` DATETIME NOT NULL,
	MODIFY COLUMN `updated_at` DATETIME NOT NULL;
